cargo-features = ["per-package-target"]

[package]
name = "host_api"
version = "0.1.0"
edition = "2021"
forced-target = "wasm32-wasi"

[dependencies]
host_api_sys = { path = "../host_api_sys" }
bytemuck = "1.13.1"
